/**
 * Compile content/blog/{id,en}/*.mdx → src/data/blog/posts.generated.ts
 */
import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import matter from "gray-matter";
import { marked } from "marked";
import { readingStatsFromHtml } from "./blog-reading.mjs";

const ROOT = path.resolve(".");
const CONTENT = path.join(ROOT, "content/blog");
const OUT = path.join(ROOT, "src/data/blog/posts.generated.ts");
const LANGS = ["id", "en"];

let codeToHtml = async (code, lang) =>
  `<pre class="blog-code-fallback"><code>${escapeHtml(code)}</code></pre>`;

try {
  const shiki = await import("shiki");
  codeToHtml = (code, lang) =>
    shiki.codeToHtml(code, {
      lang: lang || "text",
      theme: "github-dark",
    });
} catch {
  console.warn("shiki not installed — blog code blocks without highlight");
}

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

async function markdownToHtml(md) {
  const re = /```(\w*)\n([\s\S]*?)```/g;
  let last = 0;
  let out = "";
  let m;
  while ((m = re.exec(md)) !== null) {
    out += marked.parse(md.slice(last, m.index));
    out += await codeToHtml(m[2].replace(/\n$/, ""), m[1]);
    last = m.index + m[0].length;
  }
  out += marked.parse(md.slice(last));
  return out;
}

async function loadPosts() {
  const posts = [];
  for (const lang of LANGS) {
    const dir = path.join(CONTENT, lang);
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".mdx") && !file.endsWith(".md")) continue;
      const raw = fs.readFileSync(path.join(dir, file), "utf8");
      const { data, content } = matter(raw);
      const slug = file.replace(/\.(mdx|md)$/, "");
      const html = await markdownToHtml(content);
      const { wordCount, readingTimeMinutes } = readingStatsFromHtml(html);
      const row = {
        slug,
        lang,
        title: String(data.title ?? slug),
        description: String(data.description ?? ""),
        date: String(data.date ?? ""),
        tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
        html,
        wordCount,
        readingTimeMinutes,
      };
      if (data.ogImage) row.ogImage = String(data.ogImage);
      posts.push(row);
    }
  }
  posts.sort((a, b) => (a.date < b.date ? 1 : -1));
  return posts;
}

const posts = await loadPosts();
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `/* AUTO-GENERATED by scripts/build-blog.mjs — do not edit */
import type { BlogPost } from "@/types/blog";

export const blogPostsGenerated: BlogPost[] = ${JSON.stringify(posts, null, 2)} as BlogPost[];
`,
);
console.log("blog:", posts.length, "posts");

spawnSync(process.execPath, ["scripts/generate-sitemap.mjs"], {
  cwd: ROOT,
  stdio: "inherit",
});