/**
 * Regenerate public/sitemap.xml with static routes + blog posts from generated data.
 * Run after build-blog.mjs (prebuild).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const SITE =
  process.env.VITE_SITE_URL?.replace(/\/$/, "") || "https://appvibe.web.id";

function urlBlock(loc, idHref, enHref, changefreq, priority) {
  const id = idHref ?? loc;
  const en = enHref ?? loc;
  return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="id" href="${id}" />
    <xhtml:link rel="alternate" hreflang="en" href="${en}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${id}" />
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

/** Pairs: [idPath, enPath, changefreq, priority] */
const staticPairs = [
  ["/", "/en", "weekly", "1.0"],
  ["/layanan", "/en/services", "monthly", "0.9"],
  ["/portfolio", "/en/portfolio", "weekly", "0.9"],
  ["/demo", "/en/demos", "weekly", "0.9"],
  ["/industri", "/en/industries", "monthly", "0.8"],
  ["/tentang", "/en/about", "monthly", "0.8"],
  ["/kontak", "/en/contact", "monthly", "0.8"],
  ["/blog", "/en/blog", "weekly", "0.85"],
  ["/uses", "/en/uses", "monthly", "0.6"],
];

const portfolioSlugs = [
  "company-profile",
  "webinar-landing",
  "klinik",
  "properti",
  "lead-dashboard",
];

const demoAppPaths = [
  ["demo/company-profile", "demos/company-profile"],
  ["demo/webinar-landing", "demos/webinar-landing"],
  ["demo/klinik", "demos/klinik"],
  ["demo/properti", "demos/properti"],
  ["demo/lead-dashboard", "demos/lead-dashboard"],
];

function loadBlogSlugs() {
  const genPath = path.join(root, "src/data/blog/posts.generated.ts");
  if (!fs.existsSync(genPath)) return [];
  const raw = fs.readFileSync(genPath, "utf8");
  const slugs = new Set();
  for (const m of raw.matchAll(/"slug":\s*"([^"]+)"/g)) slugs.add(m[1]);
  return [...slugs];
}

const blocks = [];

for (const [idPath, enPath, freq, pri] of staticPairs) {
  blocks.push(
    urlBlock(`${SITE}${idPath}`, `${SITE}${idPath}`, `${SITE}${enPath}`, freq, pri),
  );
  blocks.push(
    urlBlock(`${SITE}${enPath}`, `${SITE}${idPath}`, `${SITE}${enPath}`, freq, pri),
  );
}

for (const slug of portfolioSlugs) {
  const id = `${SITE}/portfolio/${slug}`;
  const en = `${SITE}/en/portfolio/${slug}`;
  blocks.push(urlBlock(id, id, en, "monthly", "0.75"));
  blocks.push(urlBlock(en, id, en, "monthly", "0.75"));
}

for (const [idSeg, enSeg] of demoAppPaths) {
  const id = `${SITE}/${idSeg}`;
  const en = `${SITE}/en/${enSeg}`;
  blocks.push(urlBlock(id, id, en, "monthly", "0.7"));
  blocks.push(urlBlock(en, id, en, "monthly", "0.7"));
}

for (const slug of loadBlogSlugs()) {
  const id = `${SITE}/blog/${slug}`;
  const en = `${SITE}/en/blog/${slug}`;
  const lastmod = new Date().toISOString().slice(0, 10);
  blocks.push(`  <url>
    <loc>${id}</loc>
    <xhtml:link rel="alternate" hreflang="id" href="${id}" />
    <xhtml:link rel="alternate" hreflang="en" href="${en}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${id}" />
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`);
  blocks.push(`  <url>
    <loc>${en}</loc>
    <xhtml:link rel="alternate" hreflang="id" href="${id}" />
    <xhtml:link rel="alternate" hreflang="en" href="${en}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${id}" />
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`);
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${blocks.join("\n")}
</urlset>
`;

const out = path.join(root, "public/sitemap.xml");
fs.writeFileSync(out, xml);
console.log("wrote", out, "urls:", blocks.length);